### ISSUE TITLE
No map shown in individual activity page

### ISSUE THREAD

**Issue by jantonz** [dreeveapp/dreeve#363]
**Describe the bug**
There is no map shown in the activities. I mean in the URL http://<strava-statistics-instance>/activities#activity/activity-xxxxxxxxxxx.html
Instead, this images shows:

![Image](https://github.com/user-attachments/assets/55c8bdaf-bcca-4625-a871-6f9e58f678a1)

I may have a culprit. In Strava the map shows correctly, meaning the activity is correctly geo-tracked. However, the activity was not directly created by Strava: it was (automatically) imported from MiFitness (rather, I think MiFitness sends it to Strava).

**To Reproduce**
Go to the activity URL.

**Expected behavior**
A map should be shown instead of the default image.

**Provide your docker compose config**
I'm using the default docker-compose.yml and .env, no changes.

* be sure to redact sensitive information
* include docker-compose.yml
* include .env

**Environment configuration**

Please run `docker compose exec app bin/console app:debug:environment`
on your host machine and copy/paste the output here.
If this output is not included, we won't be able to help you

I don't think it's relevant but I will post it if necessary.

**Screenshots**

**Comment by robiningelbrecht** [comment]
@jantonz what type of activity is this?

**Comment by jantonz** [comment]
This is a run activity but the same happens in a riding activity.

**Comment by robiningelbrecht** [comment]
@jantonz can you email me your database please?

**Comment by robiningelbrecht** [comment]
@jantonz does this happen for all your activities?

**Comment by jantonz** [comment]
After further inspection: no, it does not happen for all the activities. Let me quote myself because I think I have some support for this:

> I may have a culprit. In Strava the map shows correctly, meaning the activity is correctly geo-tracked. However, the activity was not directly created by Strava: it was (automatically) imported from MiFitness (rather, I think MiFitness sends it to Strava).

I have some runs from years ago that were logged using the Strava app itself, and the map in those activities show OK. So it does look like this has something to do with this behavior. Hopefully is something to do with the format in which MiFitness sends the geolocation to Strava.

I need some pointers on how to send you the database (or only the relevant info if possible).

**Comment by robiningelbrecht** [comment]
@jantonz the database should be located in 'storage/database/strava.db'

**Comment by jantonz** [comment]
Database sent! Thank you for taking a look 😃

**Comment by robiningelbrecht** [comment]
Thanks! I'll keep you up to date via this issue

**Comment by robiningelbrecht** [comment]
@jantonz can you share an activity id of an activity that has this issue? You can copy/paste the activity id from the URI:

`http:///activities#activity/activity-xxxxxxxxxxx.html`

**Comment by jantonz** [comment]
Sure! This activity does not have a map: 13794833560
Only the oldest 7 activities have a map, so if you want more examples you can find any other run/cycling activity besides those 7.

**Comment by robiningelbrecht** [comment]
@jantonz Just checked the raw data Strava's API returned for that activity and there is no geodata available for that activity or any of the new activities:

<img width="318" alt="Image" src="https://github.com/user-attachments/assets/a39586f6-215f-4599-807e-cda2afe2dec1" />

"summary_polyline" should not be empty if there is valid geo data

**Comment by jantonz** [comment]
Would this be related?

https://www.reddit.com/r/Strava/comments/1aznzww/strava_api_not_showing_map_summary_polyline/?rdt=52090

**Comment by robiningelbrecht** [comment]
@jantonz yes indeed, what's your map visibility in the settings?

**Comment by jantonz** [comment]
All hidden:

![Image](https://github.com/user-attachments/assets/1e4d27e8-4ab4-4b77-ab12-8c565d172e0b)

It must be this. I’ll make the next activity map visible, and won’t get back to you if it works as expected, so you’ll be able to assume it was this.

I think it’s worth mentioning it somewhere in the docs, in case other users find themselves in this situation.

Thank you for the effort! The project does indeed reflect it!

If I may I have two somewhat related questions:
- Do the “maps” in the run/cycling activities show in the heatmap? Or only “routes” show there? Judging by the wording in the app I’d say only routes; I think it would be of interest to make a heatmap out of all geolocated activities, regardless of them following a “route” or not. 
- if I were to make visible the map of all my past activities, which would be the easiest way of adding the map to Strava-statistics? I’m assuming it would be deleting the database?

Thank you again!

**Comment by robiningelbrecht** [comment]
* the heatmap shows only routes indeed
* You can just update your activities on strava and they will be updated on the next import ;)

**Comment by jantonz** [comment]
Cool! I’ll do that. And again, if I don’t report back, it means everything went smoothly.

Are you open to add this “activity (not only route) heatmap” feature? In another issue ofc, not hijacking this one.

**Comment by robiningelbrecht** [comment]
Can you give an example of such activity? Not sure what you mean

**Comment by jantonz** [comment]
Sure. Let's say the activity 1987264289, which is one of my activities that has a map, it's geolocated. I understood before that this activity would not be shown in the heatmap. Have I understood correctly? I may have misinterpreted you previously.

**Comment by robiningelbrecht** [comment]
The heatmap is a collection of all your activity's polylines (routes). So if there is no polyline, what would we add to the heatmap then?

**Comment by jantonz** [comment]
My bad, I did indeed understood you wrongly before. 

I was referring to Strava "routes" before when I asked about how the heatmap in strava-statsitics work:

![Image](https://github.com/user-attachments/assets/7e77133c-4d7d-4799-ae02-9e54ea4f68a2)

But strava-statistics already has what I wanted: the heatmap shows the polylines of all activities with polylines, not only the "routes" as Strava calls them. I was confused. Does it make sense?

**Comment by Ahmosys** [comment]
Hello @jantonz, for me you're absolutely right! Strava generates a polyline by assembling multiple coordinates (latitude & longitude). So, even if it's not an official "route" as long as Strava provides a valid polyline for the activity, it should be displayed correctly.

**Comment by robiningelbrecht** [comment]
@jantonz does this mean I can close this issue?

**Comment by jantonz** [comment]
Hello,

After changing the map visibility in Strava, the map does not show (yet) in strava-statistics. And I think it’s not cache-related as I tried in an incognito window as well. I think the import already happened but I’m not sure.  I’d want to test:
- adding a new Activity and see if that shows ok
- wait for the activity I changed the map visibility in, and see if it updates in strava-statistics tomorrow
- there’s also a Strava configuration “activity privacy”, which I have set to “only you”. If the latter does not work I’d go for changing this and see.

**Comment by robiningelbrecht** [comment]
@jantonz you can just run 

`docker compose exec app bin/console app:strava:import-data` 
`docker compose exec app bin/console app:strava:build-files` 

to import your data and build the html files again

**Comment by jantonz** [comment]
@robiningelbrecht of course, good call! After run the commands you showed, which went smoothly, I have two insights:

- After importing a new run activity to Strava, with the map set as not hidden, and after running the commands, I can confirm the map in strava-statistics shows alright! The logs showed `=> Imported activity "Morning Run - 07-03-2025"`
- The activity that was originally added to Strava with the map set as hidden; that afterwards I edited to make the map not hidden; after running the commands the map in strava-statistics does not show. The logs showed `Updated activity "Lunch Run - 05-03-2025"`

Hope this helps! I can delete the database and re-import everything again, but I'm not doing that yet in case this is something you want to pursue and I could test.

**Comment by robiningelbrecht** [comment]
@jantonz Could you email me your database again so I can check if it's a bug in this app or not?

**Comment by jantonz** [comment]
Done 👍

**Comment by robiningelbrecht** [comment]
@jantonz checked the data for your activity `Updated activity "Lunch Run - 05-03-2025"` and the polyline has been imported. So that's good. But indeed, the map is still not rendering. After some digging I found a little bug.

**Comment by robiningelbrecht** [comment]
@jantonz fix has been merged. Will be released in the next (`v0.4.25`) version. Thanks for your time!!

**Comment by jantonz** [comment]
Happy to help! Thanks for your time 💪🏽

**Comment by PrimozR** [comment]
Is there an outline of what is required on Strava's side for the map to work properly? Do the activities need to be public, does the data have to be shared for heatmaps, etc.

I managed to get some of the maps working by publishing all the activities, but not for all of them - it looks like it's hit or miss.
